parcelRequire=function(e,r,n,t){var i="function"==typeof parcelRequire&&parcelRequire,o="function"==typeof require&&require;function u(n,t){if(!r[n]){if(!e[n]){var f="function"==typeof parcelRequire&&parcelRequire;if(!t&&f)return f(n,!0);if(i)return i(n,!0);if(o&&"string"==typeof n)return o(n);var c=new Error("Cannot find module '"+n+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[n][1][r]||r},p.cache={};var l=r[n]=new u.Module(n);e[n][0].call(l.exports,p,l,l.exports,this)}return r[n].exports;function p(e){return u(p.resolve(e))}}u.isParcelRequire=!0,u.Module=function(e){this.id=e,this.bundle=u,this.exports={}},u.modules=e,u.cache=r,u.parent=i,u.register=function(r,n){e[r]=[function(e,r){r.exports=n},{}]};for(var f=0;f<n.length;f++)u(n[f]);if(n.length){var c=u(n[n.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=c:"function"==typeof define&&define.amd?define(function(){return c}):t&&(this[t]=c)}return u}({"yc17":[function(require,module,exports) {
module.exports=(async({mongoose:n,url:e})=>{if(0==n.connection.readyState){n.Promise=global.Promise;let c="";try{await n.connect(e,{useNewUrlParser:!0})}catch(o){c=o.message}finally{console.log(1===n.connection.readyState?`DB : connected @ ${n.connection.host}:${n.connection.port} - DB :  ${n.connection.name} `:`DB : not connected : ${c}`)}}return n.connection});
},{}],"MqUa":[function(require,module,exports) {
"use strict";function e(){return"DEV"===t()}function t(){const e=process.env.NODE_ENV.toLowerCase();switch(!0){case!e:return console.log("!!!!! Application mode not defined in .env file / web server"),"Undefined";case e.toLowerCase().includes("prod"):return"PROD";case e.toLowerCase().includes("dev"):return"DEV"}}function o(e){return process.env[e]||""}function r({template:e,parameters:t}){return t.forEach(t=>{e=e.replace(t.key,t.value)}),e}Object.defineProperty(exports,"__esModule",{value:!0}),exports.isDevelopmentMode=e,exports.setting=o,exports.selector=r,exports.elementCount=exports.attribute=void 0,require("dotenv").config();const n=({page:e})=>e.evaluate((sel,ses)),s=({document:e},t,o)=>e.querySelector(t).getAttribute(o);exports.attribute=s;const c=async({page:e},t)=>(await e.$$(t)).length;exports.elementCount=c;
},{}],"zShk":[function(require,module,exports) {
module.exports=require("./unbound").bind(null,{mongoose:require("mongoose"),url:require("../helpers/helpers").setting("DB_URI_DEV")});
},{"./unbound":"yc17","../helpers/helpers":"MqUa"}],"l5Os":[function(require,module,exports) {
const e=require("mongoose");e.Promise=global.Promise;const t=new e.Schema({sessionID:Number,sessionDateTime:Date,seatsLeft:Number,sessionSeatsAuditedOn:{type:Date,default:Date.now,select:!1},sessionBookingURL:String,created:{type:Date,default:Date.now,select:!1},updated:{type:Date,default:Date.now,select:!1}});module.exports=e.model("Session",t);
},{}],"xOuY":[function(require,module,exports) {
const e=require("mongoose");e.Promise=global.Promise;const t=new e.Schema({cinemaID:Number,cinemaState:String,cinemaName:String,created:{type:Date,default:Date.now,select:!1},updated:{type:Date,default:Date.now,select:!1},sessions:[require("./model.Session").schema]});module.exports=e.model("Cinema",t);
},{"./model.Session":"l5Os"}],"t1kF":[function(require,module,exports) {
const e=require("mongoose"),o=e.Schema;e.Promise=global.Promise;const t=new o({movieID:Number,movieTitle:String,created:{type:Date,default:Date.now,select:!1},updated:{type:Date,default:Date.now,select:!1},cinemas:[require("./model.Cinema").schema]});module.exports=e.model("Movie",t);
},{"./model.Cinema":"xOuY"}],"sz/J":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.getMovieByTitle=exports.getMovieByID=exports.getMovies=void 0;const e=require("../database")(),t=require("./model.Movie"),i=require("./model.Cinema"),o=require("./model.Session"),s=async()=>await t.find();exports.getMovies=s;const r=async e=>await t.findById(e);exports.getMovieByID=r;const a=async e=>await t.findOne({movieTitle:e});exports.getMovieByTitle=a;
},{"../database":"zShk","./model.Movie":"t1kF","./model.Cinema":"xOuY","./model.Session":"l5Os"}],"dmRD":[function(require,module,exports) {
const{GraphQLSchema:e,GraphQLObjectType:i,GraphQLInt:s,GraphQLString:t,GraphQLList:n}=require("graphql"),r=require("../database-crud/controller"),o=new i({name:"Movie",description:"Movies showing in Event Cinemas",fields:()=>({id:{type:t,resolve:e=>e.id},movieID:{type:s,resolve:e=>e.movieID},title:{type:t,resolve:e=>e.movieTitle},cinemas:{type:new n(a),resolve:e=>e.cinemas}})}),a=new i({name:"Cinema",description:"Event Cinemas' theatre",fields:()=>({cinemaID:{type:s,resolve:e=>e.cinemaID},sessions:{type:new n(l),resolve:e=>e.sessions}})}),l=new i({name:"Session",description:"Screenings in a given theatre",fields:()=>({id:{type:s,resolve:e=>e.id},sessionID:{type:s,resolve:e=>e.sessionID},availableSeats:{type:s,resolve:e=>e.seatsLeft},time:{type:t,resolve:e=>e.sessionDateTime.toString()},ticketURL:{type:t,resolve:e=>e.sessionBookingURL}})});module.exports=new e({query:new i({name:"Query",description:"screening data from Event Cinemas for a given Indian movies ",fields:{byMovieTitle:{type:o,args:{title:{type:t}},resolve:async(e,i,s)=>{return await r.getMovieByTitle(i.title)}},byMovieID:{type:o,args:{id:{type:t}},resolve:async(e,i,s)=>{return await r.getMovieByID(i.id)}},allMovies:{type:new n(o),resolve:async(e,i,s)=>{return await r.getMovies()}}}})});
},{"../database-crud/controller":"sz/J"}],"eMEv":[function(require,module,exports) {
const e=require("express"),r=require("express-graphql"),s=e(),i=require("./graphql/schema"),g=require("./helpers/helpers");s.use("/graph",r(e=>({schema:i,graphiql:!0}))),s.listen(g.setting("PORT")),console.log(`Listening ... on ${g.setting("PORT")}`);
},{"./graphql/schema":"dmRD","./helpers/helpers":"MqUa"}]},{},["eMEv"], null)
//# sourceMappingURL=/server.map